---
- name: Clone fetch latest branch
  ansible.builtin.git:
    repo: "{{ fetch_github_repo }}"
    dest: "{{ local_checkout_dir }}"
    single_branch: yes
    version: "{{ fetch_version }}"
  tags: fetch_build
- name: Git checkout
  ansible.builtin.git:
    repo: "{{ fetch_github_repo }}"
    dest: "{{ local_checkout_dir }}"
    version: "{{ fetch_version }}"
  tags: fetch_build
- name: Run 'install' target as root
  community.general.make:
    chdir: "{{ local_checkout_dir }}"
    target: install
  become: true
  tags: fetch_build
