---
- name: Init fetchd 
  command: "{{ fetchd_binary_location }} init {{ moniker|quote }} --chain-id {{ chain_id|quote }} --home /home/fetch/.fetchd "
  args:
    creates: "{{ fetch_HOME }}/.fetchd"
  ignore_errors: yes
  tags: fresh_node
- name: backup configs
  shell: cp $HOME/.fetchd/data/priv_validator_state.json $HOME/.fetchd/priv_validator_state.json.backup
  args:
    executable: /bin/bash
- name: Download Genisis and check (sha256)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/fetchai/genesis-fetchhub/fetchhub-4/fetchhub-4/data/genesis_migrated_5300200.json
    dest: /home/fetch/.fetchd/config/genesis.json
    checksum: sha256:fe5fe42dc375ae33268c88cb03fe0c030c96f08ad96ad21921c58fd02fe711c9
- name: change ownership of genesis to fetch:fetch 
  file:  
    path: "{{ fetch_HOME }}/.fetchd/config/genesis.json"
    mode: '0644'
    owner: fetch
    group: fetch
  tags: genesis_download
