---
- import_tasks: build.yml
  become: yes
  become_user: fetch
#  become_flags: '--login'
  tags: fetchd_build
- import_tasks: init.yml
  become: yes
  become_user: fetch
#  become_flags: '--login'
  #become_method: sudo
  #become_flags: '-u fetch /bin/bash'
  tags: fresh_node
- import_tasks: config.yml
  become: yes
  become_user: fetch
#  become_flags: '--login'
  #become_method: sudo
  #become_flags: '-u fetch /bin/sh'  
  tags: init
#- import_tasks: setup.yml
#  become: yes
#  become_user: fetch
#  become_flags: '--login'
  #become_method: sudo
  #become_flags: '-u fetch /bin/bash'
#  tags: fresh_node
- import_tasks: service.yml
  #become: true
  tags: run
- import_tasks: service_check.yml
  #become: true 
  tags: service_check 
#- import_tasks: copy_binaries.yml
#  become: true 
#  become_user: root
#  tags: bin_swap
#- import_tasks: logging.yml
#  become: true
#  tags: logging