---
- name: install service script
  copy:
    src: ../templates/fetchd.service.j2
    dest: /etc/systemd/system/fetchd.service
    owner: root
    group: root
    mode: u+rw
  tags: service_install
- name: enable fetchd.service
  systemd:
    name: fetchd
    enabled: true
  tags: service_install
- name: reload fetchd.service
  systemd:
    name: fetchd
    daemon_reload: true
  tags: fetch
#- name: start fetchd
#  systemd:
#    name: fetchd
#    state: started
#  tags: servoce_install
