---
- name: Apt update
  ansible.builtin.apt:
    update_cache: yes
  tags: apt_tasks
- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: yes
  tags: apt_tasks
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - gcc
    - jq
    - make
    - net-tools
    - snapd
  tags: apt_tasks
- name: Install go channel 1.18/stable --classic
  community.general.snap:
    name: go
    classic: true
    channel: 1.18/stable
  tags: apt_tasks
