---
- name: copy ip4tables rules
  copy:
    src: templates/rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 600
  tags: firewall_install
- name: enable firewall rules
  shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash
  tags: firewall_install