---
- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
- name: Ensure group "fetch" exists
  ansible.builtin.group:
    name: fetch
    state: present
- name: Add the user fetch
  ansible.builtin.user:
    name: fetch
    shell: /bin/bash
    groups: admin,fetch,sys
    append: yes

# Replaced with snap
#- name: Add env variables to include Go
#  blockinfile:
#    path: "/home/fetch/.bashrc"
#    block: |
#      export GOROOT=/usr/local/go
#      export GOPATH=$HOME/go
#      export GO111MODULE=on
#      export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
#    backup: no
